### ISSUE TITLE
Improve terminology used in the UI

### ISSUE THREAD

**Issue by orhoj** [Concordium/concordium-ledger-app#4]
**Task description**
The current application uses a lot of technical terms:
- PRF key 
- IdCredSec
- IdCredPub
- RegIdCred
- RegId
- Identity provider
- Revocation threshold.
The terms are part of the transactions being signed, but if the user does not understand what it means, then they are effectively signing a transaction that they do not understand. The technical terms have to be replaced by easier to understand terms, or come together with some form of description.

**Comment by shjortConcordium** [comment]
- PRF key and IdCredSec
	These are both exported when we create identities/accounts/credentials.
	So they could be exported togther with the message:
	"Create Credential"
	"ID #N"

- PRF key
	This is exported when we need to decrypt or make shielded transfers/transfer to shielded.
	I propose that we change the export to:
	"Allow Decryption"
	"ID #N"

(IdCredSec is not exported without PRF key)

- IdCredPub
 Appears in the PublicInformationForIp, which we sign when making an identity.
	I propose that we don't display it, as it infeasible for the user to validate it anyway.
	
- RegIdCred
	Shown when signing credential deployment.
	After the credential has been made, we refer to this value as CredId (Credential identifier),
	So rename it to CredId.	
	
- RegId
	Shown when signing PublicInformationForIp.
	This is the same as RegIdCred, the name is just only used for the initial credential,
	So rename it to CredId.

- Identity provider
	The identifier of the Identity provider is contained in the credential deployment information.
	I propose that we don't display it, as it infeasible for the user to validate it anyway.

- Revocation Threshold ("Revoke threshold" on the ledger)
	Shown when creating new credentials.
	Rename to Anonymity Revocation threshold/AR threshold.
	I believe that we should be able to explain this to the user, though currently they don't choose it themselves, so that might be confusing.
