### ISSUE TITLE
Allow Mac users to double click install.sh

### ISSUE THREAD

**Issue by andreaslyn** [Concordium/concordium-ledger-app#47]
**Description**
Based on support issue 1048, it seems that Mac users are unable to double click the the install.sh script, due to working in home directory when double clicking.

**Steps to Reproduce**
Run make, then double click install.sh (I have not verified that this fails), but seems to be the case in support issue 1048.

**Expected Result**
The app gets installed

**Actual Result**

**Versions**
- Software Version 2.0.3
- Ledger Version 2.1.0

**Comment by andreaslyn** [comment]
It can be fixed by changing the relative paths in `Makefile` to paths relative to install.sh. For example, use `$ROOT/bin/app.hex` instead of `bin/app.hex`, where ROOT=$(dirname "$0").

**Comment by orhoj** [comment]
Will not do according to the above reasoning.
