### ISSUE TITLE
Ledger description is still Amount(GTU) for multisig simple transfer 

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-ledger-app#48]
**Bug Description**
Ledger description is still Amount(GTU) for signing a multisig simple transfer. Should be Amount(CCD) instead.

**Steps to Reproduce**
- sign a multisig simple transfer
- run through transaction on Ledger

**Expected Result**
Ledger displays CCD.

**Actual Result**
Ledger displays GTU.

**Versions**
- DW 1.3.1
- Ledger CCD app 2.0.1
- Ledger firmware 2.0.0

**Comment by shjortConcordium** [comment]
This has been changed to `Amount` (no unit) in 2.0.3. (which we only released for firmware 2.1.0)

**Comment by orhoj** [comment]
As this has already been fixed in `2.0.3`, and as it does not make sense to release a new version for the old firmware, I am closing this issue.
